In [ ]:
import pandas as pd
a=["jwalitha",'ramya','durga','pallavi','sadwika','mahathi','deepthi']
r=pd.Series(a,index=[67,43,44,89,34,45,23])
print(r)

67    jwalitha
43       ramya
44       durga
89     pallavi
34     sadwika
45     mahathi
23     deepthi
dtype: object

In [ ]:
df=pd.read_csv("/content/diabetcsv.csv")
print(df)

     preg  plas  pres  skin  insu  mass   pedi  age            class
0       6   148    72    35     0  33.6  0.627   50  tested_positive
1       1    85    66    29     0  26.6  0.351   31  tested_negative
2       8   183    64     0     0  23.3  0.672   32  tested_positive
3       1    89    66    23    94  28.1  0.167   21  tested_negative
4       0   137    40    35   168  43.1  2.288   33  tested_positive
..    ...   ...   ...   ...   ...   ...    ...  ...              ...
763    10   101    76    48   180  32.9  0.171   63  tested_negative
764     2   122    70    27     0  36.8  0.340   27  tested_negative
765     5   121    72    23   112  26.2  0.245   30  tested_negative
766     1   126    60     0     0  30.1  0.349   47  tested_positive
767     1    93    70    31     0  30.4  0.315   23  tested_negative

[768 rows x 9 columns]

In [ ]:
df=pd.read_csv("/content/grades_withnulls.csv")
print(df)

     Names Initials  SEM1  SEM2  SEM3 Grade  Placed
0      Joe        K   9.8  10.0   9.9    A+       1
1   Rajesh        M   8.9   9.1   9.3     A       1
2   Kissan        V   9.9   9.8  10.0     A       0
3     Mary        N   7.7   8.0   NaN     B       0
4     Jeen        K   9.8   9.1   9.9    A+       1
5      Raj        M   8.9   9.1   9.3     A       1
6   Hassan        V   9.9   9.0   9.2     A       1
7     Mari        N   7.7   8.0   7.1     B       1
8     Jess        K   NaN   9.1   9.9    A+       1
9   Rajini        M   NaN   9.1   9.3     A       0
10   Kiran        V   NaN   9.3   9.2     A       0
11    Maya        N   7.7   8.0   7.1     B       0
12   Jolin        K   9.8   9.1   9.9    A+       1
13  Rajesh        M   8.9   9.1   9.3     A       1
14    Riya        M   9.3   9.9  10.0     A       1
15    Sana        V   9.9   9.3   9.2     A       0
16    Mark        N   7.7   8.0   7.0     B       0

In [ ]:
df=pd.read_excel("/content/diabetes.xls")
print(df)

     preg  plas  pres  skin  insu  mass   pedi  age            class
0       6   148    72    35     0  33.6  0.627   50  tested_positive
1       1    85    66    29     0  26.6  0.351   31  tested_negative
2       8   183    64     0     0  23.3  0.672   32  tested_positive
3       1    89    66    23    94  28.1  0.167   21  tested_negative
4       0   137    40    35   168  43.1  2.288   33  tested_positive
..    ...   ...   ...   ...   ...   ...    ...  ...              ...
763    10   101    76    48   180  32.9  0.171   63  tested_negative
764     2   122    70    27     0  36.8  0.340   27  tested_negative
765     5   121    72    23   112  26.2  0.245   30  tested_negative
766     1   126    60     0     0  30.1  0.349   47  tested_positive
767     1    93    70    31     0  30.4  0.315   23  tested_negative

[768 rows x 9 columns]

In [ ]:
df=pd.read_excel("/content/diabetes.xls",sheet_name=1)
print(df)

   23   94  28.1  0.167  21  tested_negative
0  35  168  43.1  2.288  33  tested_positive
1   0    0  25.6  0.201  30  tested_negative
2  32   88  31.0  0.248  26  tested_positive
3   0    0  35.3  0.134  29  tested_negative
4  45  543  30.5  0.158  53  tested_positive
5   0    0   0.0  0.232  54  tested_positive
6   0    0  37.6  0.191  30  tested_negative
7   0    0  38.0  0.537  34  tested_positive
8   0    0  27.1  1.441  57  tested_negative
9  23  846  30.1  0.398  59  tested_positive

In [ ]:
df=pd.read_csv("/content/grades_withnulls.csv")
print(df.head())
print(df.tail(n=10))

    Names Initials  SEM1  SEM2  SEM3 Grade  Placed
0     Joe        K   9.8  10.0   9.9    A+       1
1  Rajesh        M   8.9   9.1   9.3     A       1
2  Kissan        V   9.9   9.8  10.0     A       0
3    Mary        N   7.7   8.0   NaN     B       0
4    Jeen        K   9.8   9.1   9.9    A+       1
     Names Initials  SEM1  SEM2  SEM3 Grade  Placed
7     Mari        N   7.7   8.0   7.1     B       1
8     Jess        K   NaN   9.1   9.9    A+       1
9   Rajini        M   NaN   9.1   9.3     A       0
10   Kiran        V   NaN   9.3   9.2     A       0
11    Maya        N   7.7   8.0   7.1     B       0
12   Jolin        K   9.8   9.1   9.9    A+       1
13  Rajesh        M   8.9   9.1   9.3     A       1
14    Riya        M   9.3   9.9  10.0     A       1
15    Sana        V   9.9   9.3   9.2     A       0
16    Mark        N   7.7   8.0   7.0     B       0

In [ ]:
df=pd.read_csv("/content/grades_withnulls.csv")
print(df.describe)

<bound method NDFrame.describe of      Names Initials  SEM1  SEM2  SEM3 Grade  Placed
0      Joe        K   9.8  10.0   9.9    A+       1
1   Rajesh        M   8.9   9.1   9.3     A       1
2   Kissan        V   9.9   9.8  10.0     A       0
3     Mary        N   7.7   8.0   NaN     B       0
4     Jeen        K   9.8   9.1   9.9    A+       1
5      Raj        M   8.9   9.1   9.3     A       1
6   Hassan        V   9.9   9.0   9.2     A       1
7     Mari        N   7.7   8.0   7.1     B       1
8     Jess        K   NaN   9.1   9.9    A+       1
9   Rajini        M   NaN   9.1   9.3     A       0
10   Kiran        V   NaN   9.3   9.2     A       0
11    Maya        N   7.7   8.0   7.1     B       0
12   Jolin        K   9.8   9.1   9.9    A+       1
13  Rajesh        M   8.9   9.1   9.3     A       1
14    Riya        M   9.3   9.9  10.0     A       1
15    Sana        V   9.9   9.3   9.2     A       0
16    Mark        N   7.7   8.0   7.0     B       0>

In [ ]:
df=pd.read_csv("/content/grades_withnulls.csv")
print(df.describe().T)

        count      mean       std  min  25%  50%  75%   max
SEM1     14.0  8.992857  0.929404  7.7  8.0  9.1  9.8   9.9
SEM2     17.0  9.000000  0.647109  8.0  9.0  9.1  9.3  10.0
SEM3     16.0  9.100000  1.057670  7.0  9.2  9.3  9.9  10.0
Placed   17.0  0.588235  0.507300  0.0  0.0  1.0  1.0   1.0

In [ ]:
df=pd.read_csv("/content/grades_withnulls.csv")
print(df.shape) #get no.of rows and columns
print(df.shape[0]) #get no.of rows only
print(df.shape[1]) #get the no.of columns only

(17, 7)
17
7

In [ ]:
df=pd.read_csv("/content/grades_withnulls.csv")
print(df.columns)

Index(['Names', 'Initials', 'SEM1', 'SEM2', 'SEM3', 'Grade', 'Placed'], dtype='object')

In [ ]:
df=pd.read_csv("/content/grades_withnulls.csv")
df2=df.copy()
df2.loc[2:5,'SEM1']=0
df2.head(7)
df2.isnull().head(7)
df2.isnull().tail(7)
df2.isnull().sum()
print(df['SEM1'])#extracting column
print(df2[['SEM1','Names']])

0     9.8
1     8.9
2     9.9
3     7.7
4     9.8
5     8.9
6     9.9
7     7.7
8     NaN
9     NaN
10    NaN
11    7.7
12    9.8
13    8.9
14    9.3
15    9.9
16    7.7
Name: SEM1, dtype: float64
    SEM1   Names
0    9.8     Joe
1    8.9  Rajesh
2    0.0  Kissan
3    0.0    Mary
4    0.0    Jeen
5    0.0     Raj
6    9.9  Hassan
7    7.7    Mari
8    NaN    Jess
9    NaN  Rajini
10   NaN   Kiran
11   7.7    Maya
12   9.8   Jolin
13   8.9  Rajesh
14   9.3    Riya
15   9.9    Sana
16   7.7    Mark

In [ ]:
df=pd.read_csv("/content/grades_withnulls.csv")
print(df[df.index==1])#single row

    Names Initials  SEM1  SEM2  SEM3 Grade  Placed
1  Rajesh        M   8.9   9.1   9.3     A       1

In [ ]:
df=pd.read_csv("/content/grades_withnulls.csv")
print(df[df.index.isin(range(2,5))])#multiple rows

    Names Initials  SEM1  SEM2  SEM3 Grade  Placed
2  Kissan        V   9.9   9.8  10.0     A       0
3    Mary        N   7.7   8.0   NaN     B       0
4    Jeen        K   9.8   9.1   9.9    A+       1

In [ ]:
df=pd.read_csv("/content/grades_withnulls.csv")
print(df2.loc[3])#printing row as series

Names       Mary
Initials       N
SEM1         0.0
SEM2         8.0
SEM3         NaN
Grade          B
Placed         0
Name: 3, dtype: object

In [ ]:
df=pd.read_csv("/content/grades_withnulls.csv")
(df2.loc[6:11,'SEM1']==None)#row range
print(df2)
df2.loc[[1,2,3]]

     Names Initials  SEM1  SEM2  SEM3 Grade  Placed
0      Joe        K   9.8  10.0   9.9    A+       1
1   Rajesh        M   8.9   9.1   9.3     A       1
2   Kissan        V   0.0   9.8  10.0     A       0
3     Mary        N   0.0   8.0   NaN     B       0
4     Jeen        K   0.0   9.1   9.9    A+       1
5      Raj        M   0.0   9.1   9.3     A       1
6   Hassan        V   9.9   9.0   9.2     A       1
7     Mari        N   7.7   8.0   7.1     B       1
8     Jess        K   NaN   9.1   9.9    A+       1
9   Rajini        M   NaN   9.1   9.3     A       0
10   Kiran        V   NaN   9.3   9.2     A       0
11    Maya        N   7.7   8.0   7.1     B       0
12   Jolin        K   9.8   9.1   9.9    A+       1
13  Rajesh        M   8.9   9.1   9.3     A       1
14    Riya        M   9.3   9.9  10.0     A       1
15    Sana        V   9.9   9.3   9.2     A       0
16    Mark        N   7.7   8.0   7.0     B       0

    Names Initials  SEM1  SEM2  SEM3 Grade  Placed
1  Rajesh        M   8.9   9.1   9.3     A       1
2  Kissan        V   0.0   9.8  10.0     A       0
3    Mary        N   0.0   8.0   NaN     B       0

In [ ]:
df=pd.read_csv("/content/grades_withnulls.csv")
df2.loc[10:15,['Names','Grade',]]

     Names Grade
10   Kiran     A
11    Maya     B
12   Jolin    A+
13  Rajesh     A
14    Riya     A
15    Sana     A

In [ ]:
df=pd.read_csv("/content/grades_withnulls.csv")
df2.iloc[10:14,:3]#[row,column]

     Names Initials  SEM1
10   Kiran        V   NaN
11    Maya        N   7.7
12   Jolin        K   9.8
13  Rajesh        M   8.9

In [ ]:
df=pd.read_csv("/content/grades_withnulls.csv")
df2.loc[:7,['Names']]

    Names
0     Joe
1  Rajesh
2  Kissan
3    Mary
4    Jeen
5     Raj
6  Hassan
7    Mari

In [ ]:
df=pd.read_csv("/content/grades_withnulls.csv")
df2.loc[df['Names']=='Rajesh']#PRINTING ONE NAME HOW MANY TIMES THAT NAME REPEATS

     Names Initials  SEM1  SEM2  SEM3 Grade  Placed
1   Rajesh        M   8.9   9.1   9.3     A       1
13  Rajesh        M   8.9   9.1   9.3     A       1

In [ ]:
df=pd.read_csv("/content/grades_withnulls.csv")
df[df.Grade=='A']
df[df.SEM2==10]
df.loc[df['SEM1']>9.8,['Names']]

     Names
2   Kissan
6   Hassan
15    Sana

In [ ]:
df=pd.read_csv("/content/grades_withnulls.csv")
df3=df2.copy()
print(df3)

     Names Initials  SEM1  SEM2  SEM3 Grade  Placed
0      Joe        K   9.8  10.0   9.9    A+       1
1   Rajesh        M   8.9   9.1   9.3     A       1
2   Kissan        V   0.0   9.8  10.0     A       0
3     Mary        N   0.0   8.0   NaN     B       0
4     Jeen        K   0.0   9.1   9.9    A+       1
5      Raj        M   0.0   9.1   9.3     A       1
6   Hassan        V   9.9   9.0   9.2     A       1
7     Mari        N   7.7   8.0   7.1     B       1
8     Jess        K   NaN   9.1   9.9    A+       1
9   Rajini        M   NaN   9.1   9.3     A       0
10   Kiran        V   NaN   9.3   9.2     A       0
11    Maya        N   7.7   8.0   7.1     B       0
12   Jolin        K   9.8   9.1   9.9    A+       1
13  Rajesh        M   8.9   9.1   9.3     A       1
14    Riya        M   9.3   9.9  10.0     A       1
15    Sana        V   9.9   9.3   9.2     A       0
16    Mark        N   7.7   8.0   7.0     B       0

In [ ]:
df=pd.read_csv("/content/grades_withnulls.csv")
df3=df2.copy()
df3.dropna(inplace=True,axis=1)#inplace says not to reflect that changes in the df
print(df3)

     Names Initials  SEM2 Grade  Placed
0      Joe        K  10.0    A+       1
1   Rajesh        M   9.1     A       1
2   Kissan        V   9.8     A       0
3     Mary        N   8.0     B       0
4     Jeen        K   9.1    A+       1
5      Raj        M   9.1     A       1
6   Hassan        V   9.0     A       1
7     Mari        N   8.0     B       1
8     Jess        K   9.1    A+       1
9   Rajini        M   9.1     A       0
10   Kiran        V   9.3     A       0
11    Maya        N   8.0     B       0
12   Jolin        K   9.1    A+       1
13  Rajesh        M   9.1     A       1
14    Riya        M   9.9     A       1
15    Sana        V   9.3     A       0
16    Mark        N   8.0     B       0

In [ ]:
df=pd.read_csv("/content/grades_withnulls.csv")
df3=df2.copy()
df3.dropna(inplace=True,how='all')#drops both rows and columns of Nan
print(df3)

     Names Initials  SEM1  SEM2  SEM3 Grade  Placed
0      Joe        K   9.8  10.0   9.9    A+       1
1   Rajesh        M   8.9   9.1   9.3     A       1
2   Kissan        V   0.0   9.8  10.0     A       0
3     Mary        N   0.0   8.0   6.4     B       0
4     Jeen        K   0.0   9.1   9.9    A+       1
5      Raj        M   0.0   9.1   9.3     A       1
6   Hassan        V   9.9   9.0   9.2     A       1
7     Mari        N   7.7   8.0   7.1     B       1
8     Jess        K   6.4   9.1   9.9    A+       1
9   Rajini        M   6.4   9.1   9.3     A       0
10   Kiran        V   6.4   9.3   9.2     A       0
11    Maya        N   7.7   8.0   7.1     B       0
12   Jolin        K   9.8   9.1   9.9    A+       1
13  Rajesh        M   8.9   9.1   9.3     A       1
14    Riya        M   9.3   9.9  10.0     A       1
15    Sana        V   9.9   9.3   9.2     A       0
16    Mark        N   7.7   8.0   7.0     B       0

In [ ]:
df=pd.read_csv("/content/grades_withnulls.csv")
mv=df2['SEM1'].mean()
df2=df2.fillna(mv)
print(df2)
print(mv)

     Names Initials  SEM1  SEM2  SEM3 Grade  Placed
0      Joe        K   9.8  10.0   9.9    A+       1
1   Rajesh        M   8.9   9.1   9.3     A       1
2   Kissan        V   0.0   9.8  10.0     A       0
3     Mary        N   0.0   8.0   6.4     B       0
4     Jeen        K   0.0   9.1   9.9    A+       1
5      Raj        M   0.0   9.1   9.3     A       1
6   Hassan        V   9.9   9.0   9.2     A       1
7     Mari        N   7.7   8.0   7.1     B       1
8     Jess        K   6.4   9.1   9.9    A+       1
9   Rajini        M   6.4   9.1   9.3     A       0
10   Kiran        V   6.4   9.3   9.2     A       0
11    Maya        N   7.7   8.0   7.1     B       0
12   Jolin        K   9.8   9.1   9.9    A+       1
13  Rajesh        M   8.9   9.1   9.3     A       1
14    Riya        M   9.3   9.9  10.0     A       1
15    Sana        V   9.9   9.3   9.2     A       0
16    Mark        N   7.7   8.0   7.0     B       0
6.400000000000001